import { useEffect, useState } from 'react';
import { ArrowLeft, Mail, Loader2, Copy, ExternalLink, Lock } from 'lucide-react';
import { api } from '../lib/api';

export default function EmailDetail({ id, onBack }) {
  const [email, setEmail] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let alive = true;
    setLoading(true);
    api.email(id).then(d => alive && setEmail(d)).catch(e => alive && setError(e.message)).finally(() => alive && setLoading(false));
    return () => { alive = false; };
  }, [id]);

  if (loading) return <DetailShell onBack={onBack}><div className="animate-pulse h-96 bg-white rounded-lg ring-1 ring-ink-100" /></DetailShell>;
  if (error) return <DetailShell onBack={onBack}><p className="text-red-700">{error}</p></DetailShell>;
  if (!email) return null;

  const draft = makeDraft(email);

  function copyDraft() {
    navigator.clipboard.writeText(draft);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function openInGmail() {
    const params = new URLSearchParams({
      view: 'cm',
      to: extractEmail(email.from) ?? '',
      su: `Re: ${email.subject ?? ''}`,
      body: draft,
    });
    window.open(`https://mail.google.com/mail/?${params.toString()}`, '_blank');
  }

  return (
    <DetailShell onBack={onBack}>
      <article>
        <div className="flex items-center gap-2 mb-2">
          <span className={`pill pill-${email.priority}`}>{email.priority}</span>
          <span className={`pill pill-cat-${email.category}`}>{email.category}</span>
          {email.action_required && <span className="pill pill-action">action required</span>}
        </div>
        <h1 className="font-display text-3xl lg:text-4xl tracking-tight leading-tight mt-2">
          {email.subject || '(no subject)'}
        </h1>
        <div className="mt-3 flex items-baseline justify-between text-sm text-ink-500">
          <p>{email.from}</p>
          <p className="font-mono text-xs">{email.date}</p>
        </div>

        <div className="mt-8 card p-6">
          <p className="font-mono text-[10px] uppercase tracking-widest text-flame">AI summary · workers ai · {email.latency_ms}ms</p>
          <p className="mt-3 text-lg leading-relaxed text-ink-900 font-display">{email.summary ?? '(summary pending)'}</p>
          {email.suggested_action && (
            <div className="mt-5 pt-5 border-t border-ink-100">
              <p className="font-mono text-[10px] uppercase tracking-widest text-ink-500">suggested action</p>
              <p className="mt-2 text-ink-900">{email.suggested_action}</p>
            </div>
          )}
        </div>

        <div className="mt-6 card p-6">
          <div className="flex items-center justify-between">
            <p className="font-mono text-[10px] uppercase tracking-widest text-ink-500">draft reply</p>
            <div className="flex gap-2">
              <button onClick={copyDraft} className="btn-ghost">
                <Copy size={14} /> {copied ? 'copied!' : 'copy'}
              </button>
              <button onClick={openInGmail} className="btn-primary text-sm py-1.5">
                <ExternalLink size={14} /> open in Gmail
              </button>
            </div>
          </div>
          <pre className="mt-4 whitespace-pre-wrap font-sans text-ink-900 leading-relaxed text-[15px]">{draft}</pre>
        </div>

        <div className="mt-6 card p-6 bg-ink-50/40">
          <div className="flex items-center gap-2">
            <Lock size={14} className="text-sage" />
            <p className="font-mono text-[10px] uppercase tracking-widest text-ink-500">privacy receipt</p>
          </div>
          <p className="mt-2 text-sm text-ink-500 leading-relaxed">
            This summary was generated by Llama 3.1 8B running on Cloudflare Workers AI, encrypted with AES-GCM-256 before storage in R2, and decrypted on demand. No external AI vendor saw the email body. Verify in your{' '}
            <a href="https://dash.cloudflare.com/?to=/:account/ai/ai-gateway" target="_blank" rel="noreferrer" className="text-flame underline underline-offset-4 decoration-flame/40">
              AI Gateway dashboard
            </a>.
          </p>
        </div>
      </article>
    </DetailShell>
  );
}

function DetailShell({ onBack, children }) {
  return (
    <div className="min-h-screen px-6 lg:px-12 py-8 max-w-3xl mx-auto">
      <button onClick={onBack} className="btn-ghost mb-6">
        <ArrowLeft size={14} /> back to inbox
      </button>
      {children}
    </div>
  );
}

function makeDraft(email) {
  const senderName = (email.from ?? '').split('<')[0].trim().replace(/^"|"$/g, '') || 'there';
  const first = senderName.split(' ')[0];
  if (email.suggested_action) {
    return `Hi ${first},\n\n${draftFromAction(email.suggested_action)}\n\nThanks,\n[your name]`;
  }
  return `Hi ${first},\n\nThanks for your email. Following up shortly.\n\nThanks,\n[your name]`;
}

function draftFromAction(action) {
  const a = action.toLowerCase();
  if (a.includes('reply') || a.includes('respond')) return 'Got your message — responding now.';
  if (a.includes('availability') || a.includes('schedule')) return "I'm available — let's get this on the calendar. Sending a few times shortly.";
  if (a.includes('confirm')) return 'Confirmed — go ahead.';
  if (a.includes('review')) return "Taking a look and will follow up with thoughts soon.";
  return action;
}

function extractEmail(from) {
  if (!from) return null;
  const m = from.match(/<([^>]+)>/);
  return m ? m[1] : from;
}
